import { useState, useCallback, useMemo } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  FolderOpen,
  Folder,
  FileText,
  FileCode,
  FileJson,
  File,
  ChevronRight,
  ChevronDown,
  Search,
  LayoutGrid,
  FolderTree,
  ArrowLeftRight,
  Download,
  X,
} from 'lucide-react'
import { useToast } from '@/contexts/ToastContext'

// ═══════════════════════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════════════════════

type NodeType = 'folder' | 'file'
type PlatformKey = 'claudecode' | 'codex' | 'hermes' | 'opencode' | 'shared'

interface FileNode {
  id: string
  name: string
  type: NodeType
  path: string
  children?: FileNode[]
  content?: string
  platform?: PlatformKey
  size?: string
  modified?: string
}

// ═══════════════════════════════════════════════════════════════════════════════
// MOCK DATA — workspace/ 目录结构
// ═══════════════════════════════════════════════════════════════════════════════

const WORKSPACE_ROOT: FileNode = {
  id: 'root',
  name: 'workspace',
  type: 'folder',
  path: 'workspace',
  children: [
    {
      id: 'chat-001',
      name: 'chat-001',
      type: 'folder',
      path: 'workspace/chat-001',
      children: [
        {
          id: 'chat-001-claudecode',
          name: 'claudecode',
          type: 'folder',
          path: 'workspace/chat-001/claudecode',
          platform: 'claudecode',
          children: [
            {
              id: 'chat-001-claudecode-main',
              name: 'main.py',
              type: 'file',
              path: 'workspace/chat-001/claudecode/main.py',
              platform: 'claudecode',
              size: '4.2 KB',
              modified: '2026-05-17 14:32',
              content: `#!/usr/bin/env python3
"""
Auth module — refactored by Claude Code
Handles JWT issuance, validation, and refresh.
"""

import asyncio
from datetime import datetime, timedelta
from typing import Optional

import jwt
from fastapi import HTTPException, status
from passlib.context import CryptContext

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30


def verify_password(plain: str, hashed: str) -> bool:
    return pwd_context.verify(plain, hashed)


def get_password_hash(password: str) -> str:
    return pwd_context.hash(password)


def create_access_token(
    data: dict,
    secret: str,
    expires_delta: Optional[timedelta] = None,
) -> str:
    to_encode = data.copy()
    expire = datetime.utcnow() + (expires_delta or timedelta(minutes=15))
    to_encode.update({"exp": expire})
    return jwt.encode(to_encode, secret, algorithm=ALGORITHM)


async def validate_token(token: str, secret: str) -> dict:
    try:
        payload = jwt.decode(token, secret, algorithms=[ALGORITHM])
        return payload
    except jwt.ExpiredSignatureError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token has expired",
        )
    except jwt.InvalidTokenError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid token",
        )
`,
            },
          ],
        },
        {
          id: 'chat-001-codex',
          name: 'codex',
          type: 'folder',
          path: 'workspace/chat-001/codex',
          platform: 'codex',
          children: [
            {
              id: 'chat-001-codex-utils',
              name: 'utils.ts',
              type: 'file',
              path: 'workspace/chat-001/codex/utils.ts',
              platform: 'codex',
              size: '2.8 KB',
              modified: '2026-05-17 14:35',
              content: `/**
 * Shared utilities — generated by Codex
 */

export interface AsyncResult<T> {
  data?: T;
  error?: Error;
  status: 'idle' | 'loading' | 'success' | 'error';
}

export function debounce<T extends (...args: any[]) => void>(
  fn: T,
  delay: number
): (...args: Parameters<T>) => void {
  let timer: ReturnType<typeof setTimeout>;
  return (...args) => {
    clearTimeout(timer);
    timer = setTimeout(() => fn(...args), delay);
  };
}

export function useAsyncOperation<T, A extends unknown[]>(
  operation: (...args: A) => Promise<T>
) {
  const [state, setState] = useState<AsyncResult<T>>({
    status: 'idle',
    data: undefined,
    error: undefined,
  });

  const execute = async (...args: A): Promise<T> => {
    setState({ status: 'loading' });
    try {
      const data = await operation(...args);
      setState({ status: 'success', data });
      return data;
    } catch (error) {
      const err = error instanceof Error ? error : new Error('Unknown error');
      setState({ status: 'error', error: err });
      throw err;
    }
  };

  return { ...state, execute };
}
`,
            },
          ],
        },
      ],
    },
    {
      id: 'chat-002',
      name: 'chat-002',
      type: 'folder',
      path: 'workspace/chat-002',
      children: [
        {
          id: 'chat-002-claudecode',
          name: 'claudecode',
          type: 'folder',
          path: 'workspace/chat-002/claudecode',
          platform: 'claudecode',
          children: [
            {
              id: 'chat-002-claudecode-router',
              name: 'router.py',
              type: 'file',
              path: 'workspace/chat-002/claudecode/router.py',
              platform: 'claudecode',
              size: '1.5 KB',
              modified: '2026-05-17 10:12',
              content: `from fastapi import APIRouter
from .handlers import UserHandler, OrderHandler

router = APIRouter(prefix="/api/v1")
router.include_router(UserHandler.router, tags=["users"])
router.include_router(OrderHandler.router, tags=["orders"])
`,
            },
          ],
        },
      ],
    },
    {
      id: 'task-002',
      name: 'task-002',
      type: 'folder',
      path: 'workspace/task-002',
      children: [
        {
          id: 'task-002-claudecode',
          name: 'claudecode',
          type: 'folder',
          path: 'workspace/task-002/claudecode',
          platform: 'claudecode',
          children: [
            {
              id: 'task-002-claudecode-api',
              name: 'api.py',
              type: 'file',
              path: 'workspace/task-002/claudecode/api.py',
              platform: 'claudecode',
              size: '6.1 KB',
              modified: '2026-05-17 16:45',
              content: `"""
REST API layer — multi-agent task output (Claude Code)
"""

from fastapi import FastAPI, Depends, HTTPException
from pydantic import BaseModel
from typing import List, Optional

app = FastAPI(title="Multi-Agent API", version="1.0.0")

class Item(BaseModel):
    id: int
    name: str
    description: Optional[str] = None
    price: float

@app.get("/items", response_model=List[Item])
async def list_items():
    return [
        Item(id=1, name="Alpha", price=19.99),
        Item(id=2, name="Beta", price=29.99),
    ]

@app.post("/items", response_model=Item)
async def create_item(item: Item):
    return item
`,
            },
          ],
        },
        {
          id: 'task-002-hermes',
          name: 'hermes',
          type: 'folder',
          path: 'workspace/task-002/hermes',
          platform: 'hermes',
          children: [
            {
              id: 'task-002-hermes-readme',
              name: 'README.md',
              type: 'file',
              path: 'workspace/task-002/hermes/README.md',
              platform: 'hermes',
              size: '3.4 KB',
              modified: '2026-05-17 16:50',
              content: `# Multi-Agent Task Report

## Overview

This task coordinates three agents to build a complete REST API service.

## Agents Involved

| Agent | Platform | Role |
|-------|----------|------|
| Code Writer | Claude Code | API implementation |
| Documenter | Hermes | Documentation |
| Config Manager | OpenCode | LSP / tooling config |

## File Structure

\`\`\`
workspace/task-002/
├── claudecode/
│   └── api.py          ← Core API routes
├── hermes/
│   └── README.md       ← This file
└── opencode/
    └── config.json     ← Editor / LSP config
\`\`\`

## Usage

1. Install dependencies: \`pip install -r requirements.txt\`
2. Run server: \`uvicorn api:app --reload\`
3. Open docs: http://localhost:8000/docs

## Architecture Decisions

- FastAPI for async request handling
- Pydantic for validation
- Modular router pattern for scalability
`,
            },
          ],
        },
        {
          id: 'task-002-opencode',
          name: 'opencode',
          type: 'folder',
          path: 'workspace/task-002/opencode',
          platform: 'opencode',
          children: [
            {
              id: 'task-002-opencode-config',
              name: 'config.json',
              type: 'file',
              path: 'workspace/task-002/opencode/config.json',
              platform: 'opencode',
              size: '1.2 KB',
              modified: '2026-05-17 16:48',
              content: `{
  "lsp": {
    "pylsp": {
      "configurationSources": ["pycodestyle"],
      "plugins": {
        "pycodestyle": {
          "enabled": true,
          "maxLineLength": 100,
          "ignore": ["E501", "W503"]
        },
        "pydocstyle": {
          "enabled": true,
          "convention": "google"
        },
        "mypy": {
          "enabled": true,
          "live_mode": true
        }
      }
    }
  },
  "editor": {
    "tabSize": 4,
    "insertSpaces": true,
    "rulers": [100],
    "formatOnSave": true
  }
}
`,
            },
          ],
        },
      ],
    },
    {
      id: 'task-003',
      name: 'task-003',
      type: 'folder',
      path: 'workspace/task-003',
      children: [
        {
          id: 'task-003-codex',
          name: 'codex',
          type: 'folder',
          path: 'workspace/task-003/codex',
          platform: 'codex',
          children: [
            {
              id: 'task-003-codex-types',
              name: 'types.ts',
              type: 'file',
              path: 'workspace/task-003/codex/types.ts',
              platform: 'codex',
              size: '1.8 KB',
              modified: '2026-05-16 09:22',
              content: `export type TaskStatus = 'queued' | 'running' | 'completed' | 'failed' | 'paused';

export interface AgentConfig {
  id: string;
  name: string;
  platform: string;
  model: string;
  skills: string[];
}

export interface TaskStep {
  id: string;
  name: string;
  status: TaskStatus;
  agentId: string;
  output?: string;
  startedAt?: string;
  completedAt?: string;
}
`,
            },
          ],
        },
        {
          id: 'task-003-hermes',
          name: 'hermes',
          type: 'folder',
          path: 'workspace/task-003/hermes',
          platform: 'hermes',
          children: [
            {
              id: 'task-003-hermes-spec',
              name: 'spec.json',
              type: 'file',
              path: 'workspace/task-003/hermes/spec.json',
              platform: 'hermes',
              size: '0.9 KB',
              modified: '2026-05-16 09:30',
              content: `{
  "schema": "agent-task-v1",
  "title": "Content Generation Pipeline",
  "agents": ["creative-writer", "editor", "publisher"],
  "workflow": "parallel",
  "outputs": {
    "drafts": "markdown",
    "review": "json",
    "publish": "html"
  }
}
`,
            },
          ],
        },
      ],
    },
    {
      id: 'shared',
      name: 'shared',
      type: 'folder',
      path: 'workspace/shared',
      platform: 'shared',
      children: [
        {
          id: 'shared-common',
          name: 'common.css',
          type: 'file',
          path: 'workspace/shared/common.css',
          size: '2.1 KB',
          modified: '2026-05-15 08:00',
          content: `/* Shared styles across all agents */

:root {
  --brand: #1a56db;
  --brand-glow: rgba(26, 86, 219, 0.25);
  --accent-cyan: #06b6d4;
  --accent-mint: #10b981;
  --accent-coral: #ef4444;
  --accent-purple: #8b5cf6;
  --accent-amber: #f59e0b;
  --canvas: #0b0f19;
  --surface-0: #0f1525;
  --surface-1: #151d2f;
  --surface-2: #1c2640;
  --surface-3: #24304d;
  --surface-4: #2a3a5c;
  --text-primary: #e2e8f0;
  --text-secondary: #94a3b8;
  --text-tertiary: #64748b;
  --text-muted: #475569;
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: 'Inter', system-ui, -apple-system, sans-serif;
  background: var(--canvas);
  color: var(--text-primary);
  line-height: 1.5;
  -webkit-font-smoothing: antialiased;
}
`,
        },
        {
          id: 'shared-utils',
          name: 'helpers.py',
          type: 'file',
          path: 'workspace/shared/helpers.py',
          size: '1.4 KB',
          modified: '2026-05-15 08:05',
          content: `"""Shared helper utilities for all agents."""

import hashlib
import json
from pathlib import Path
from typing import Any


def stable_hash(obj: Any) -> str:
    """Deterministic hash for caching / deduplication."""
    payload = json.dumps(obj, sort_keys=True, default=str)
    return hashlib.sha256(payload.encode()).hexdigest()[:16]


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def read_jsonl(path: Path) -> list[dict]:
    results = []
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line:
                results.append(json.loads(line))
    return results
`,
        },
      ],
    },
  ],
}

// ═══════════════════════════════════════════════════════════════════════════════
// UTILITIES
// ═══════════════════════════════════════════════════════════════════════════════

const PLATFORM_META: Record<PlatformKey, { icon: typeof FileCode; color: string; label: string }> = {
  claudecode: { icon: FileCode, color: '#d97706', label: 'Claude Code' },
  codex: { icon: File, color: '#1a56db', label: 'Codex' },
  hermes: { icon: FileText, color: '#10b981', label: 'Hermes' },
  opencode: { icon: FileJson, color: '#f59e0b', label: 'OpenCode' },
  shared: { icon: FolderOpen, color: '#64748b', label: 'Shared' },
}

function getFileIcon(filename: string) {
  const ext = filename.split('.').pop()?.toLowerCase()
  switch (ext) {
    case 'py':
    case 'js':
    case 'ts':
    case 'jsx':
    case 'tsx':
      return FileCode
    case 'json':
      return FileJson
    case 'md':
    case 'txt':
      return FileText
    default:
      return File
  }
}

function getLangFromFilename(filename: string): string {
  const ext = filename.split('.').pop()?.toLowerCase()
  const map: Record<string, string> = {
    py: 'python',
    js: 'javascript',
    ts: 'typescript',
    jsx: 'jsx',
    tsx: 'tsx',
    json: 'json',
    md: 'markdown',
    css: 'css',
    html: 'html',
  }
  return map[ext || ''] || 'text'
}

// ═══════════════════════════════════════════════════════════════════════════════
// FILE TREE COMPONENT
// ═══════════════════════════════════════════════════════════════════════════════

function FileTreeNode({
  node,
  depth,
  expanded,
  onToggle,
  selectedPath,
  onSelect,
  searchQuery,
}: {
  node: FileNode
  depth: number
  expanded: Set<string>
  onToggle: (id: string) => void
  selectedPath: string
  onSelect: (node: FileNode) => void
  searchQuery: string
}) {
  const isExpanded = expanded.has(node.id)
  const isFolder = node.type === 'folder'
  const isSelected = node.path === selectedPath

  // Filter: if search is active, only show matching nodes or their parents
  const matchesSearch =
    !searchQuery || node.name.toLowerCase().includes(searchQuery.toLowerCase())

  const childMatches =
    isFolder &&
    node.children?.some(
      (c) =>
        c.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        c.children?.some((cc) => cc.name.toLowerCase().includes(searchQuery.toLowerCase()))
    )

  const shouldShow = !searchQuery || matchesSearch || childMatches || depth === 0

  if (!shouldShow) return null

  const indent = depth * 14
  const platformMeta = node.platform ? PLATFORM_META[node.platform] : undefined

  return (
    <div>
      {/* Node row */}
      <button
        onClick={() => {
          if (isFolder) onToggle(node.id)
          else onSelect(node)
        }}
        className={`group flex w-full items-center gap-2 rounded-lg py-1.5 pr-2 text-left transition-colors ${
          isSelected && !isFolder
            ? 'bg-surface-2 text-text-primary'
            : 'text-text-secondary hover:bg-surface-1 hover:text-text-primary'
        }`}
        style={{ paddingLeft: `${indent + 8}px` }}
      >
        {isFolder ? (
          <>
            {isExpanded ? (
              <ChevronDown className="h-3.5 w-3.5 shrink-0 text-text-muted" />
            ) : (
              <ChevronRight className="h-3.5 w-3.5 shrink-0 text-text-muted" />
            )}
            {node.platform && platformMeta ? (
              <platformMeta.icon
                className="h-4 w-4 shrink-0"
                style={{ color: platformMeta.color }}
              />
            ) : (
              <FolderOpen className="h-4 w-4 shrink-0 text-accent-amber" />
            )}
          </>
        ) : (
          <>
            <span className="w-3.5 shrink-0" />
            {(() => {
              const Icon = getFileIcon(node.name)
              return <Icon className="h-4 w-4 shrink-0 text-text-tertiary" />
            })()}
          </>
        )}
        <span className={`truncate text-sm ${isSelected && !isFolder ? 'font-medium text-text-primary' : ''}`}>
          {node.name}
        </span>
        {node.platform && platformMeta && isFolder && depth >= 2 && (
          <span
            className="ml-auto shrink-0 text-[10px] font-medium"
            style={{ color: platformMeta.color }}
          >
            {platformMeta.label}
          </span>
        )}
        {node.type === 'file' && node.size && (
          <span className="ml-auto shrink-0 text-[10px] text-text-muted">{node.size}</span>
        )}
      </button>

      {/* Children */}
      <AnimatePresence initial={false}>
        {isFolder && isExpanded && node.children && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.15 }}
            className="overflow-hidden"
          >
            {node.children.map((child) => (
              <FileTreeNode
                key={child.id}
                node={child}
                depth={depth + 1}
                expanded={expanded}
                onToggle={onToggle}
                selectedPath={selectedPath}
                onSelect={onSelect}
                searchQuery={searchQuery}
              />
            ))}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

// ═══════════════════════════════════════════════════════════════════════════════
// CODE PREVIEW
// ═══════════════════════════════════════════════════════════════════════════════

function CodePreview({ filename, content }: { filename: string; content: string }) {
  const lang = getLangFromFilename(filename)
  const lines = content.split('\n')

  return (
    <div className="flex h-full flex-col"
    >
      {/* Toolbar */}
      <div className="flex h-10 shrink-0 items-center justify-between border-b border-surface-4 bg-surface-1 px-4"
      >
        <div className="flex items-center gap-2"
        >
          {(() => {
            const Icon = getFileIcon(filename)
            return <Icon className="h-4 w-4 text-text-tertiary" />
          })()}
          <span className="text-sm font-medium text-text-primary">{filename}</span>
          <span className="rounded bg-surface-2 px-2 py-0.5 text-[10px] font-mono text-text-tertiary">
            {lang}
          </span>
        </div>
        <div className="flex items-center gap-2"
        >
          <span className="text-xs text-text-muted">{lines.length} lines</span>
          <button
            className="flex h-7 w-7 items-center justify-center rounded-lg text-text-tertiary transition-colors hover:bg-surface-2 hover:text-text-primary"
            title="Download"
          >
            <Download className="h-3.5 w-3.5" />
          </button>
        </div>
      </div>

      {/* Code */}
      <div className="flex-1 overflow-auto bg-canvas"
      >
        <div className="flex"
        >
          {/* Line numbers */}
          <div className="sticky left-0 shrink-0 select-none border-r border-surface-4 bg-surface-1 py-4 text-right"
          >
            {lines.map((_, i) => (
              <div
                key={i}
                className="px-3 text-xs font-mono leading-6 text-text-muted"
              >
                {i + 1}
              </div>
            ))}
          </div>
          {/* Content */}
          <div className="min-w-0 flex-1 py-4"
          >
            <pre className="text-sm font-mono leading-6 text-text-primary"
            >
              <code>{content}</code>
            </pre>
          </div>
        </div>
      </div>
    </div>
  )
}

// ═══════════════════════════════════════════════════════════════════════════════
// EMPTY STATE
// ═══════════════════════════════════════════════════════════════════════════════

function EmptyPreview() {
  return (
    <div className="flex h-full flex-col items-center justify-center gap-4"
    >
      <div className="flex h-16 w-16 items-center justify-center rounded-2xl border border-dashed border-surface-4 bg-surface-1"
      >
        <ArrowLeftRight className="h-8 w-8 text-text-muted" />
      </div>
      <div className="text-center"
      >
        <h3 className="text-sm font-medium text-text-secondary"
        >Select a file to preview</h3>
        <p className="mt-1 max-w-[280px] text-xs text-text-muted"
        >
          Browse the shared workspace. All platform files live here — Claude Code, Codex, Hermes, OpenCode.
        </p>
      </div>
      <div className="flex flex-wrap justify-center gap-2"
      >
        {Object.entries(PLATFORM_META).map(([key, meta]) => (
          <span
            key={key}
            className="inline-flex items-center gap-1.5 rounded-lg border border-surface-4 bg-surface-1 px-3 py-1.5 text-xs"
          >
            <meta.icon className="h-3.5 w-3.5" style={{ color: meta.color }} />
            <span style={{ color: meta.color }}>{meta.label}</span>
          </span>
        ))}
      </div>
    </div>
  )
}

// ═══════════════════════════════════════════════════════════════════════════════
// MAIN PAGE
// ═══════════════════════════════════════════════════════════════════════════════

export default function FileWorkspace() {
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedNode, setSelectedNode] = useState<FileNode | null>(null)
  const [expanded, setExpanded] = useState<Set<string>>(
    () => new Set(['root', 'chat-001', 'task-002'])
  )
  const [layoutMode, setLayoutMode] = useState<'tree' | 'grid'>('tree')
  const { addToast } = useToast()

  const toggleExpand = useCallback((id: string) => {
    setExpanded((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }, [])

  const expandAll = useCallback(() => {
    const allIds = new Set<string>()
    function collect(node: FileNode) {
      allIds.add(node.id)
      node.children?.forEach(collect)
    }
    collect(WORKSPACE_ROOT)
    setExpanded(allIds)
  }, [])

  const collapseAll = useCallback(() => {
    setExpanded(new Set(['root']))
  }, [])

  // Flat file list for grid view
  const flatFiles = useMemo(() => {
    const files: FileNode[] = []
    function walk(node: FileNode, path: string) {
      if (node.type === 'file') {
        files.push({ ...node, name: `${path}/${node.name}` })
      }
      node.children?.forEach((c) => walk(c, path ? `${path}/${node.name}` : node.name))
    }
    WORKSPACE_ROOT.children?.forEach((c) => walk(c, ''))
    return files.filter((f) =>
      !searchQuery || f.name.toLowerCase().includes(searchQuery.toLowerCase())
    )
  }, [searchQuery])

  const selectedFileCount = useMemo(() => {
    let count = 0
    function walk(node: FileNode) {
      if (node.type === 'file') count++
      node.children?.forEach(walk)
    }
    WORKSPACE_ROOT.children?.forEach(walk)
    return count
  }, [])

  const selectedFolderCount = useMemo(() => {
    let count = 0
    function walk(node: FileNode) {
      if (node.type === 'folder') count++
      node.children?.forEach(walk)
    }
    WORKSPACE_ROOT.children?.forEach(walk)
    return count
  }, [])

  return (
    <div className="flex h-full w-full"
    >
      {/* ── LEFT SIDEBAR: File Tree ── */}
      <div className="flex w-[340px] shrink-0 flex-col border-r border-surface-4 bg-canvas"
      >
        {/* Header */}
        <div className="flex h-12 items-center justify-between border-b border-surface-4 px-4"
        >
          <div className="flex items-center gap-2"
          >
            <FolderTree className="h-5 w-5 text-accent-amber" />
            <h3 className="text-base font-medium text-text-primary font-display"
            >Files</h3>
          </div>
          <div className="flex items-center gap-1"
          >
            <button
              onClick={expandAll}
              className="flex h-7 w-7 items-center justify-center rounded-lg text-text-tertiary transition-colors hover:bg-surface-2 hover:text-text-primary"
              title="Expand all"
            >
              <ChevronDown className="h-4 w-4" />
            </button>
            <button
              onClick={collapseAll}
              className="flex h-7 w-7 items-center justify-center rounded-lg text-text-tertiary transition-colors hover:bg-surface-2 hover:text-text-primary"
              title="Collapse all"
            >
              <ChevronRight className="h-4 w-4" />
            </button>
          </div>
        </div>

        {/* Search */}
        <div className="mx-3 my-3"
        >
          <div className="relative"
          >
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-text-tertiary" />
            <input
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search files..."
              className="h-9 w-full rounded-lg bg-surface-1 pl-9 pr-3 text-sm text-text-primary placeholder:text-text-tertiary outline-none focus:ring-1 focus:ring-brand"
            />
          </div>
        </div>

        {/* Stats */}
        <div className="mx-3 mb-2 flex items-center gap-3"
        >
          <span className="text-[10px] text-text-muted"
          >
            {selectedFileCount} files
          </span>
          <span className="text-[10px] text-text-muted"
          >
            {selectedFolderCount} folders
          </span>
          <span className="text-[10px] text-text-muted"
          >
            shared workspace
          </span>
        </div>

        {/* Tree */}
        <div className="flex-1 overflow-y-auto px-2 pb-2"
        >
          {layoutMode === 'tree' ? (
            <FileTreeNode
              node={WORKSPACE_ROOT}
              depth={0}
              expanded={expanded}
              onToggle={toggleExpand}
              selectedPath={selectedNode?.path || ''}
              onSelect={(node) => {
                if (node.type === 'file') {
                  setSelectedNode(node)
                }
              }}
              searchQuery={searchQuery}
            />
          ) : (
            <div className="grid grid-cols-2 gap-2"
            >
              {flatFiles.map((file) => {
                const Icon = getFileIcon(file.name)
                const platformColor = file.platform
                  ? PLATFORM_META[file.platform]?.color
                  : '#64748b'
                return (
                  <button
                    key={file.id}
                    onClick={() => setSelectedNode(file)}
                    className={`flex flex-col items-center gap-2 rounded-xl border p-4 text-center transition-colors ${
                      selectedNode?.id === file.id
                        ? 'border-brand bg-[rgba(26,86,219,0.05)]'
                        : 'border-surface-4 bg-surface-1 hover:border-brand-muted'
                    }`}
                  >
                    <Icon
                      className="h-8 w-8"
                      style={{ color: platformColor }}
                    />
                    <span className="truncate text-xs font-medium text-text-primary w-full">
                      {file.name}
                    </span>
                    <span className="text-[10px] text-text-muted">
                      {file.size}
                    </span>
                  </button>
                )
              })}
            </div>
          )}
        </div>

        {/* Layout toggle */}
        <div className="flex items-center justify-between border-t border-surface-4 px-4 py-2"
        >
          <div className="flex items-center gap-1 rounded-lg bg-surface-1 p-0.5"
          >
            <button
              onClick={() => setLayoutMode('tree')}
              className={`flex h-6 w-6 items-center justify-center rounded transition-colors ${
                layoutMode === 'tree'
                  ? 'bg-surface-2 text-text-primary'
                  : 'text-text-tertiary hover:text-text-secondary'
              }`}
              title="Tree view"
            >
              <FolderTree className="h-3.5 w-3.5" />
            </button>
            <button
              onClick={() => setLayoutMode('grid')}
              className={`flex h-6 w-6 items-center justify-center rounded transition-colors ${
                layoutMode === 'grid'
                  ? 'bg-surface-2 text-text-primary'
                  : 'text-text-tertiary hover:text-text-secondary'
              }`}
              title="Grid view"
            >
              <LayoutGrid className="h-3.5 w-3.5" />
            </button>
          </div>
          <span className="text-[10px] text-text-muted"
          >{layoutMode} view</span>
        </div>
      </div>

      {/* ── RIGHT: Preview Area ── */}
      <div className="flex flex-1 flex-col min-w-0 bg-surface-0"
      >
        {selectedNode?.type === 'file' && selectedNode.content ? (
          <CodePreview
            filename={selectedNode.name}
            content={selectedNode.content}
          />
        ) : (
          <EmptyPreview />
        )}
      </div>
    </div>
  )
}

import { uploadFile } from '@/api/client';